resources:
  - name: repo_testspog
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: skylark05/testspog
      branch: master

jobs:
  - name: j1
    type: runSh
    steps:
      - TASK:
          script:
            - echo "hello, world"
  - name: j2
    type: runSh
    steps:
      - IN: j1
      - IN: repo_testspog
        switch: off
      - TASK:
          runtime:
            options:
              env:
                - IMG_VER_NAME: "v6.5.1"
                - IMG_VER_NAME_DASH: "v6-5-1"
          script:
            - echo "hello, world"
            - pushd $(shipctl get_resource_state repo_testspog)
            - cat foo.txt
            - shipctl replace foo.txt
            - cat foo.txt
            - popd
