jobs:
  - name: j1
    type: runSh
    steps:
      - TASK:
          script:
            - echo "hello, world"
  - name: j2
    type: runSh
    steps:
      - IN: j1
      - TASK:
          runtime:
            options:
              env:
                - IMG_VER_NAME: "v6.5.1"
                - IMG_VER_NAME_DASH: "v6-5-1"
          script:
            - echo "hello, world"
            - cat foo.txt
            - shipctl replace foo.txt
            - cat foo.txt
