resources:
  - name: repo_test_pr
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: skylark05/test_pr
      branch: master
      buildOnPullRequest: true

jobs:
  - name: j1
    type: runSh
    steps:
      - IN: repo_test_pr
        showBuildStatus: true
      - TASK:
          script:
            - echo "hello, world"
            - test_pr is now at $(shipctl get_resource_version_name repo_test_pr)
