resources:
  - name: repo_test_pr
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: skylark05/test_pr
      branch: master
      buildOnPullRequest: true

jobs:
  - name: j1
    type: runSh
    steps:
      - IN: repo_test_pr
        showBuildStatus: true
      - TASK:
          script:
            - echo "hello, world"
            - echo test_pr is now at $(shipctl get_resource_version_name repo_test_pr)
            - echo "going to sleep..."
            - sleep 600

  - name: A
    type: runSh
    steps:
      - TASK:
          script:
            - echo "hello, world"
            
  - name: B
    type: runSh
    steps:
      - IN: A
      - TASK:
          script:
            - echo "hello, world"
            
  - name: C
    type: runSh
    steps:
      - IN: A
      - TASK:
          script:
            - echo "hello, world"
            
  - name: D
    type: runSh
    steps:
      - IN: A
      - TASK:
          script:
            - echo "hello, world"
            
  - name: E
    type: runSh
    dependencyMode: strict
    steps:
      - IN: B
      - IN: C
      - IN: D
      - TASK:
          script:
            - echo "hello, world"
